name: Demo CI/CD pipeline for the session 67214 # The name of the workflow

on: # Trigger
  push:
    branches: [ main ] # Trigger the workflow on push events to the main branch
  pull_request:
    branches: [ main ] # Trigger the workflow on pull request events to the main branch
  workflow_dispatch: # Trigger the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner for the job

    steps:
    - name: Checkout code # Step to checkout the repository code
      uses: actions/checkout@v2

    - name: Setup .NET Core # Step to setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Specify the .NET Core SDK version to use

    - name: Restore dependencies # Step to restore project dependencies
      run: dotnet restore

    - name: Build # Step to build the project
      run: dotnet build --no-restore --configuration Release -o out

    - name: Test # Step to run unit tests
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Azure Login # Step to login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep Template # Step to deploy the Bicep template
      run: az deployment group create --resource-group Demo67214 --template-file arm/deploy.bicep --parameters arm/deploy.prod.parameters.json

    - name: Deploy to Azure Web App # Step to deploy the ASP.NET application to the App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: demo67214prod
        package: . /out/     